### ISSUE TITLE
strict_optional not working

### ISSUE THREAD

**Issue by aarontami** [matangover/mypy-vscode#3] opened 2019-09-05 19:45 UTC
First of all, thanks for this great extension!

I have a mypy config file set in the settings that contains
`strict_optional = False`

This should allow me to return or assign `None` to any variable, however the mypy extension is still giving me errors for this.

Any advice for how to get this working? Is this a bug?

Thanks.

**Comment by matangover** [comment] 2019-09-07 16:09
> First of all, thanks for this great extension!

You're welcome :)

> Any advice for how to get this working? Is this a bug?

I just verified that `strict_optional = False` works for me. Make sure you reload the VS Code window (using the command `Developer: Reload Window` or simply close and re-open the window) after changing the mypy config. If that doesn't help, let me know.

**Comment by aarontami** [comment] 2019-09-08 00:07
Doesn't seem to work for me, ive reloaded vscode many times.  Here's what I have.  In the mypy extension settings, I have the config file set to the full path for `mypy_py3.ini`. This file contains:

```
[mypy]
python_version = 3.6
dump_type_stats = False
incremental = True

# Flags Should always be False - for strict typing
follow_imports = normal
ignore_missing_imports = False

# Should always be True - for strict typing
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
disallow_subclassing_any = True
warn_no_return = True

# Goal is to set all to True - for strict
# in increasing level of difficulty
disallow_any_unimported = False
warn_return_any = False
disallow_any_decorated = False
strict_optional = False

# Hard to set to True - but if so, thats pretty amazing
disallow_any_generics = False
disallow_any_explicit = False
disallow_any_expr = False
warn_incomplete_stub = False
```

Which contains strict_options = False. An example of one of the errors im still seeing is:

code:
`return results, None`

Error:
```
Incompatible return value type (got "Tuple[List[Any], None]", expected "Tuple[List[Any], str]")mypy(error)
```

**Comment by matangover** [comment] 2019-09-09 22:54
Hmm, it works for me. I used the config file you posted. My workspace folder contained one file with the following content:
```python
a: int = None
```
And I don't get any error. If I set `strict_optional=True` I do get an error.

I'm using Python 3.7.4 with mypy 0.701. Which versions are you using?

Also, could you check that if you execute mypy from the command line with the same config and target folder you don't get the error?

Also, maybe post the output written in the 'mypy' category in the VS Code Output pane.

**Comment by matangover** [comment] 2019-10-03 06:55
I still can't reproduce this. Any news?

**Comment by aarontami** [comment] 2019-10-03 07:53
Sorry for the delay'd reply.  I kind of just got used to it reporting all the `None`'s as errors, heh.

I'm also using mypy version .710.  It looks like my vscode is still using python 2.7, although I thought i had pointed it to use version 3.6.

I can do some more debugging on this tomorrow.  Thanks for following up.

**Comment by matangover** [comment] 2019-11-02 00:24
Please update to mypy-vscode 0.1.4, mypyls 0.2 and mypy 0.740.
Using the instructions here:
https://github.com/matangover/mypy-vscode#updating

If you still encounter problems, let me know. Closing this because I can't reproduce.

**Closed by matangover** 2019-11-02 00:24 UTC
