### ISSUE TITLE
Can't get it work - works only with "using active interpreter" 

### ISSUE THREAD

**Issue by pitris90** [matangover/mypy-vscode#51] opened 2022-03-27 16:47 UTC
I tried to install this extension, but I can't get it work, because it always run into error code "Error running mypy in c:\Users\petrb\Documents\ib002: mypy failed with exit code 3221225477. See Output panel for details."

I explored what is causing this problem and I figured out that it probably tries to execute this command in Powershell (without *) -> * 'C:\pathtodmypy\Programs\Python\Python39\Scripts\dmypy.EXE' --status-file 'c:\pathtocode\Code\User\workspaceStorage\b250e0bde59cbbe1db0fa8d688831459\matangover.mypy\dmypy-4c61643f6415b49ce007b5195b716f4d990428d1-17100.json' run --log-file 'c:\pathtoworkspace\workspaceStorage\b250e0bde59cbbe1db0fa8d688831459\matangover.mypy\dmypy-4c61643f6415b49ce007b5195b716f4d990428d1.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable 'C:\pathtopython'*
However... when it wants to run in Powershell like this, it needs to include & before that text so it interprets as executable path. Or maybe there is different problem, but I didnt see & character in output window. And with current settings in extension I dont know how to workaround this problem when I dont want to turn on "Run Using Active Interpreter" - when I check this, it works.

**Comment by matangover** [comment] 2022-03-28 10:16
The plugin doesn't use PowerShell, so the problem is probably not related to the `&` character. Can you post the full contents of your the Mypy category in the VSCode Output panel? And also the output of running manually in the terminal `dmypy --version`?

**Comment by pitris90** [comment] 2022-03-28 10:47
Hmmm.... it seems it works now... Maybe it was caused by different extension? Or maybe because I was using MagicPython instead of Python extension by Microsoft? Because that setting ("Run Using Active Interpreter") caused me troubles when I was working with Java, so I decided to clean up my workspace extensions to use only extensions that are needed for particular workspace. And I think I was using MagicPython when I ran into this issue.. I will try to investigate it more when I will have time.

Dmypy version: dmypy 0.931

**Comment by matangover** [comment] 2022-03-28 10:55
OK, it's nice that the issue fixed itself :) For now I close the issue, if you can reproduce it please re-open and explain to me how to reproduce it. Thanks!

**Comment by pitris90** [comment] 2022-03-28 12:12
Ok, so now it works in my workspace with python files, but not in workspace with jupyter notebooks that are using python inside... Here is full output from that mypy extension: 
Mypy extension activated, version 0.2.2
Registering listener for interpreter changed event
Waiting for Python extension to load
Python extension loaded
Listener registered
[1] Check workspace: c:\Users\pitris90\Documents\ib031
Activation complete
[1] Received python path from Python extension: C:\Users\pitris90\AppData\Local\Programs\Python\Python39\python.exe
[1] Running dmypy in folder c:\Users\pitris90\Documents\ib031
'C:\Users\pitris90\AppData\Local\Programs\Python\Python39\Scripts\dmypy.EXE' --status-file 'c:\Users\pitris90\AppData\Roaming\Code\User\workspaceStorage\c4a6a906c53a6dc6bfa88936257de3da\matangover.mypy\dmypy-c6c45c66c8becc35250f3318cfdc10b131bc9d78-4184.json' run --log-file 'c:\Users\pitris90\AppData\Roaming\Code\User\workspaceStorage\c4a6a906c53a6dc6bfa88936257de3da\matangover.mypy\dmypy-c6c45c66c8becc35250f3318cfdc10b131bc9d78.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable 'C:\Users\pitris90\AppData\Local\Programs\Python\Python39\python.exe'
[1] Error running mypy in c:\Users\pitris90\Documents\ib031: mypy failed with exit code 3221225477. See Output panel for details.

**Comment by pitris90** [comment] 2022-03-28 16:15
I couldn't reopen issue, because you closed it and I am not contributer in this repo. If I closed it, I could have reopen it :D

**Comment by matangover** [comment] 2022-03-30 09:35
It seems that the dmypy daemon crashed in your case. According to Google, exit code 3221225477 "Indicates that the executed program has terminated abnormally or crashed". Can you attach the contents of the dmypy log file?

The path of the log file is written in the Output panel contents that you pasted. It is saved here:
`c:\Users\pitris90\AppData\Roaming\Code\User\workspaceStorage\c4a6a906c53a6dc6bfa88936257de3da\matangover.mypy\dmypy-c6c45c66c8becc35250f3318cfdc10b131bc9d78.log`

**Comment by matangover** [comment] 2022-05-09 07:13
@pitris90 are you still able to reproduce the bug?

**Comment by matangover** [comment] 2022-06-23 10:37
@pitris90 if you still have issues please find a new issue, thanks

**Closed** 2022-06-23 10:37 UTC
