### ISSUE TITLE
Extension reports problems from outside current workspace

### ISSUE THREAD

**Issue by ssbarnea** [matangover/mypy-vscode#59] opened 2022-08-15 07:05 UTC
First, let me thanks for creating this extension, especially as we most know that pyright is not a full replacement for running mypy.

The problem is that I see my Problems tab being spammed by mypy reported issues unrelated to current workspace, is like it is running on python (from pyenv in my case) own site-packages. It is easy to see this as distracting/spam as we cannot do anything about these. 

![](https://sbarnea.com/ss/Screen-Shot-2022-08-15-07-59-02.90.png)

Please let me know what extra info is needed in order to narrow down this bug. It seems that my targets folder is configured to `.`, even if I do not remember customizing myself. As the docs mentioned that the default should be an empty list, I attempted to remove it but when I did this, I got an error:

![](https://sbarnea.com/ss/Screen-Shot-2022-08-15-08-04-46.51.png)

It is bit weird because the `mypy.ini` from my [repository/workspace root](https://github.com/ansible/ansible-lint) does have `exclude = (build|dist|test/local-content|site-packages|~/.pyenv)` and I know for sure that mypy works fine as I use it as a pre-commit hook. Still, the mypy daemon used by this extension does not seem to properly use the same settings.

**Comment by matangover** [comment] 2022-08-15 10:14
> It seems that my targets folder is configured to ., even if I do not remember customizing myself. As the docs mentioned that the default should be an empty list, I attempted to remove it but when I did this, I got an error:

You should leave `mypy.targets` as the default, which is indeed `.`. This tells the daemon to check the entire workspace folder.

> Please let me know what extra info is needed in order to narrow down this bug
If I just clone your repo (ansible-lint) and open it in VSCode, I can't reproduce this issue (i.e. I only see problems related to the actual repo code). Can you give a step by step guide how to reproduce?

**Comment by matangover** [comment] 2022-12-03 13:57
Can you reproduce this issue or should I close it?

**Closed** 2023-02-05 19:41 UTC
