### ISSUE TITLE
[help or feature request] How to pass in "--explicit-package-bases" argument ?

### ISSUE THREAD

**Issue by JDurSyn** [matangover/mypy-vscode#78] opened 2023-08-29 09:48 UTC
As in title,

Mypy just does not run on my repo otherwise

Many thanks in advance !

**Comment by matangover** [comment] 2023-10-27 22:21
Hi, you have two options currently:

1. Add a mypy.ini file which sets this argument
2. Add this argument in the targets - workaround as described here: https://github.com/matangover/mypy-vscode/issues/35#issuecomment-887893484

**Comment by matangover** [comment] 2023-10-27 22:21
Closing this as duplicate of #35

**Closed by matangover** 2023-10-27 22:21 UTC
