### ISSUE TITLE
Python extension not found

### ISSUE THREAD

**Issue by asant-leitha** [matangover/mypy-vscode#91] opened 2024-05-27 15:24 UTC
I am using a virtual environment created with poetry at path: `/Users/asant/Library/Caches/pypoetry/virtualenvs/enrichment-consumer-YzJUiNr_-py3.12/bin/python` and the setting `mypy.runUsingActiveInterpreter` set to `true`, however I get this error:

```
Mypy extension activated, version 0.3.1
Registering listener for interpreter changed event
Python extension not found
[1] Check folder: /Users/asant/Desktop/enrichment-consumer
[1] Python extension not found
Activation complete
[1] Could not run mypy: no active interpreter. Please activate an interpreter in the Python extension or switch off the mypy.runUsingActiveInterpreter setting.
```

**Comment by matangover** [comment] 2024-05-27 15:54
Do you have the Python extension by Microsoft installed?

**Comment by asant-leitha** [comment] 2024-05-28 07:41
Yes, v2024.0.0

**Comment by matangover** [comment] 2024-06-03 18:03
Is this how it looks like on your machine?
<img width="720" alt="image" src="https://github.com/matangover/mypy-vscode/assets/5028956/33d0a5ec-832e-425d-b88f-f0376f1f93a5">
Can you send me a screenshot? The newest version of the Python extension is v2024.6.0, I'm surprised you have v2024.0.0, try updating it maybe.

**Comment by matangover** [comment] 2024-08-10 19:31
Closing because I can't reproduce this, please re-open if you have more details.

**Closed by matangover** 2024-08-10 19:31 UTC
