### ISSUE TITLE
What to do when plugin can't kill dmypy

### ISSUE THREAD

**Issue by MakonnenMak** [matangover/mypy-vscode#90] opened 2024-03-20 01:40 UTC
Specifically when we hit this line here

https://github.com/matangover/mypy-vscode/blob/d644253d21551c05d229b5d8b21680a453bf84da/src/extension.ts#L173C1-L174C1

Is there a mechanism to manually kill it ?

**Comment by matangover** [comment] 2024-06-03 18:05
Hi, I missed your post - sorry! Are you able to reproduce this problem? Does it happen often?

**Comment by matangover** [comment] 2024-08-10 19:31
Closing because I can't reproduce this issue. Please re-open if you have more details.

**Closed by matangover** 2024-08-10 19:31 UTC
